const os = required('os');
console.log(os.arch());
console.log(os.cpus());
console.log(os.freemem());
console.log(os.totalname());
console.log(os.hostname());
console.log(os.platform());
console.log(os.release());
console.log(os.type());
console.log(os.uptime());
console.log(os.userInfo());